[package]
name = "tjudge-cli"
version = "1.0.0"
edition = "2024"
authors = ["Kirill Zhikharev <zhikh.k@gmail.com>"]
license = "MIT"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
timeout-readwrite = "0.4.0"
